### ISSUE TITLE
November 16th Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#116]
Checklist/Roadmap for the next demo, in order of priority. There are associated issues for each item. Check API Documentation at: [Test Prototype API doc page](http://appcivist.littlemacondo.com:9000/api/doc) | [Your Local API doc page](https://localhost:9000/api/doc) (if you have it running locally). Be patient, the doc API is automatically generated by swagger and the UI takes some time in loading it
1. **Contributions**
   - [ ] :pushpin: #120 Improve Contribution Read/Write page
   - [ ] :pushpin: #94 Introduce "Add attachment" button and implement file uploading to IMGUR
   - [x] #87 #86 Proposals page/view for contributions of the type PROPOSAL
   - [ ] #106 Action items support
   - [x] #115 Remove campaign timeline from contribution modal
   - [ ] :pushpin: #121 Click to edit fields
2. **Assemblies and working groups**
   - [ ] #107 Add invitation support
   - [x] #67 Make sure the membership list for assemblies is correct
   - [ ] :pushpin: #84 Create a first version of the working group page and link it where is needed (following Assembly example) 
   - [ ] :pushpin: #104 Fix display of buttons according to membership
   - [x] :pushpin: #88 Changes to the creation of assembly
   - [x] #108 Filters and order by button
   - [ ] #80 Connect fastrack button to POST /assembly/{id}/campaign using default values for all the configs and adding all the themes of the assembly (before, let's do the group related pages) following the new designs in #88
   - [ ] :pushpin: #109 Empty labels and messages
   - [x] :pushpin: #65 Link contribution buttons: 
     - "Publish" => POST /assembly/{id}/contribution?space=forum
     - "Cancel" => Clean the contribution form
     - "Select Theme" => fill up options using the assembly themes 
     - "+" must open allow attaching a file  
   - [ ]  Invitations page
3. **Campaign** 
   - [x] #112 Fix milestone selected when is not in URL
   - [x] #113 Milestone not started message
   - [x] :pushpin: #114 New Campaign Creation Process 
   - [x] #78 connect list of campaign templates to API => GET /campaign/template
   - [x] #110 Remove icons of map and lists in campaign page
   - [x] #111 Fix Milestones titles for component 
   - [x] #69 Display campaign milestones time to starting/ending dates in campaign page
4. **Voting**
   - [ ] #92 Implement voting views (assigned to @valentinewallace and @yifan-li01)
   - [ ] #98 Add "Open Voting Ballot" 
5. **Home**
   - [x] #99 Fix go to campaign links
   - [x] #100 link updates
   - [ ] #101 User Profile page
   - [ ] #102 Send message modal
   - [x] #103 Fix working group links
6. **Landing page**
   - [x] #97 Link each current assembly to its assembly profile page (and create this profile page)
7. **Nav Bar**
   - [ ] Add titles of current focus after "Assemblies"
     - When in an "Assembly", name of the assembly
     - When in an "Campaign", title of campaign
     - When in an "Working Group", name of group

**Notes about JSON models**
- [Assembly](http://www.jsoneditoronline.org/?id=97b4cdfea93b8a118e19d7a7325c0c9a) (everything is returned right now, posts in forum, campaigns, including also all the content of the campaign, this will be limited in the future for more efficiency and better control access)
- [Contribution](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e91304138b1)
- [Campaign](http://www.jsoneditoronline.org/?id=e6796dc77cf32a37a4639a606bad3c48)
- [Component Instance](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e455c817)
- [Milestone](http://www.jsoneditoronline.org/?id=a1d1a89c08de9ad2b2ee736d4e9622fd)
- [Working Group](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e4575707)
- [New Assembly](http://www.jsoneditoronline.org/?id=645ab1a29503c4bbd9aaa03d103a1700)
- [New Contribution](http://www.jsoneditoronline.org/?id=9bf3de782191b0caf8ede60f672cf272) (type = FORUM_POST if it is for the forum, IDEA if it is a contribution for brainstorming, PROPOSAL if it is for the stages after brainstorming) 
- [New Campaign](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25)
- [New Working Group](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e913058f0d4)
- [Listed Assembly Profiles](http://www.jsoneditoronline.org/?id=6f27b15c8eca3b4b261a9fdbb5e21cf5)
- [List of Assembly Campaigns](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f21a171) 
- [List of Contributions](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f4fa3c7)

[New Campaign Example](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25) update. Because we cannot use ebean to merge existing a new entities in relationships, the new model now must specify which entities (themes, components) are existing in a different array.
