### ISSUE TITLE
Demo prototype final checklist 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#123]
Checklist/Roadmap for the next demo. Priorities have a :pushpin: 
1. **Landing page**
   - [x] :pushpin: New design of landing page #125 
   - [ ] :pushpin: :pushpin: Redesign the onboarding process with a focus on "managed assemblies" (e.g., a city hall and its official neighbourhood councils and org.) 
   - [ ] :pushpin: :pushpin: Implement the new onboarding process for "managed assemblies" 
   - [x] :pushpin: :pushpin: Connect the Group Signup to the new Signup as a Group including the creation of an assembly #183
2. **Translation**  #186
   - [x] :round_pushpin: :+1: Revise and finalize "english strings"
   - [x] :round_pushpin: :+1: Integrate translation strings in all the pages
   - [x] :round_pushpin: :+1: Create separate files for french, german and spanish
   - [ ] :round_pushpin: :+1: **[Mission Publique]** Translate english strings into priority languages (french and german) 
3. **Home page**
   - [x] :bug: Fix Layout of side boxes with action buttons (e.g., New Assembly) #126 
   - [ ] :new: Add an user profile modal #101
   - [ ] :new: Send message modal #102
   - [ ] :bug: Profile picture of users is not loaded on first call #185
4. **List of Assemblies Page**
   - [x] :bug: Assemblies description in list of assemblies page overflow their boxes #127
5. **New Assembly Page**
   - [x] :pushpin: :bug: Assembly icons are not shown #128
   - [ ] :bug: Add validation on the themes array when creating assemblies #184
6. **Assembly and Working Groups page**
   - [x] :pushpin: :pushpin: Invitations support in assembly and working group pages #107
   - [x] :pushpin: :pushpin: Invitation Accept/Reject page #178
   - [x] :pushpin: :pushpin: Connect "Join Assembly" Button to the API #181
   - [ ] :new: Add manage assembly button and link it to the assembly edit page #129
   - [ ] :new: Empty labels and messages #109 
   - [x] :pushpin: Show assembly and working group members with STATUS #131
   - [ ] :bug: Fix order by random in list of comments directive #135
   - [ ] :bug: Fix forum post box when the list of comment is empty #136
   - [x] :pushpin: :bug: Fix forum post box cancel link does not clear the text box #137
   - [x] :pushpin: :bug: List of themes not being shown in the forum post box #138
   - [ ] :new: Implement filter by themes #139
   - [ ] :new: Link the "+" button in new comments to the "add attachment" partial #140
   - [x] :pushpin: Link the "New Proposal Draft" in the Working Group Page to the "New Proposal Page" #141
   - [ ] :new: Add "contributions" of the members to the Working Group Page #142
   - [ ] :pushpin: Add list of proposals authored by the Working Group to the Working group Page with consensus support #143
   - [ ] :pushpin: Add a small button for "accepting" join requests in groups and assemblies #187
   - [x] :pushpin: Add list of past campaigns to the list of campaigns in the home #188
7. **New Campaign Page**
   - [x] :pushpin: :bug: Campaign fast-track campaign creation bug "ReferenceError: linkedCampaign is not defined" #130
   - [x] :bug: Fix color in visualization of campaign phases #132
   - [ ] :bug: Fix default milestones period shown (should be 6 months not 12 months) #133
   - [ ] :bug: Fix error in campaign creation that displays when the assembly has no linked assembly #134
8. **Campaign Page**
   - [x] :pushpin: Replace contribution boxes by contribution box directive in campaign pages #145
   - [ ] :pushpin: :bug: Automatically go to the current milestone depending when loading a campaign #146
   - [ ] :pushpin: :bug: If phase has passed, change message "ends" to "ended" #147
   - [x] Fix buttons not showing in "Versioning" and "Deliberation" #148
   - [ ] :bug: Fix days to start in milestone not showing in campaign page #149
9. **Contributions views and pages**
   - [x] :pushpin: Implement contribution box directive #144
   - [x] :pushpin: Improve Contribution Read/Write page #120 
   - [x] :pushpin: Introduce "Add attachment" button and implement file uploading to Amazon S3 #94 
   - [x] :pushpin: Click to edit fields #121 
   - [ ] :new: Action items support #106 
   - [x] :pushpin: Fix modal shadow showing after clicking "edit" in contribution modal #150
   - [x] :pushpin: Fix list of working group members in the contribution view/edit page #151
   - [x] :pushpin: Show list of attachments of contribution in contribution page and views #152 
   - [x] Modify upvote and downvote directive so that it only allows one vote per user #158
   - [x] :pushpin: :pushpin: Expected result: on authored contributions, an "Edit" button should be available
10. **New Working Group Page** 
    - [x] :pushpin: Connect "New Working Group" page to API #155
11. **Voting Page**
    - [x] :pushpin: :pushpin: Integrate voting Ballot UI #153
    - [x] :pushpin: :pushpin: Connect open ballot UI to API #161 
    - [x]  Add "Open Voting Ballot" #98
12. **Misc**
    - [x] Integrate "Internationalization" support #81 

**Notes about JSON models [OUTDATED]**
- [Assembly](http://www.jsoneditoronline.org/?id=97b4cdfea93b8a118e19d7a7325c0c9a) (everything is returned right now, posts in forum, campaigns, including also all the content of the campaign, this will be limited in the future for more efficiency and better control access)
- [Contribution](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e91304138b1)
- [Campaign](http://www.jsoneditoronline.org/?id=e6796dc77cf32a37a4639a606bad3c48)
- [Component Instance](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e455c817)
- [Milestone](http://www.jsoneditoronline.org/?id=a1d1a89c08de9ad2b2ee736d4e9622fd)
- [Working Group](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e4575707)
- [New Assembly](http://www.jsoneditoronline.org/?id=645ab1a29503c4bbd9aaa03d103a1700)
- [New Contribution](http://www.jsoneditoronline.org/?id=9bf3de782191b0caf8ede60f672cf272) (type = FORUM_POST if it is for the forum, IDEA if it is a contribution for brainstorming, PROPOSAL if it is for the stages after brainstorming) 
- [New Campaign](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25)
- [New Working Group](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e913058f0d4)
- [Listed Assembly Profiles](http://www.jsoneditoronline.org/?id=6f27b15c8eca3b4b261a9fdbb5e21cf5)
- [List of Assembly Campaigns](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f21a171) 
- [List of Contributions](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f4fa3c7)

[New Campaign Example](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25) update. Because we cannot use ebean to merge existing a new entities in relationships, the new model now must specify which entities (themes, components) are existing in a different array.
