### ISSUE TITLE
Refactoring UI routes step 1

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1266]
The current routing system presents too many complications and issues, that are constantly solved with redirections. These redirections often happen already after the UI attempts to contact the backend, with error responses from the backend due to incorrect authentication. 
 
To finally fix this, we need to change the current routing system into a simpler one, with only one type of URLs (instead of the two types of 'public' vs 'private' URLs we have now).  

- [ ] Remove routes that use the numerical ids of assemblies, campaigns, contributions, groups
- [ ] On each main controller (assemblies, campaign dashboard, contribution page, working group page), make sure that the controller decides whether the visitor is anonymous or not based on the presence of the user in the local storage rather than looking at the types of parameters of the routes 
    * One problem here might be that the user object is not yet available when the controller takes a look, so we need to make sure that this user object loading on signing in/signing up is complete before we get to this point.
- [ ] If the user is logged in, ask the backend for the corresponding numerical IDs of the campaign, assembly, contribution, group, whose uuids we have from the route. 
     * Only when we have these ids, the rest of the controller can work as intended as the distinction on the backend endpoints is necessary to implement authorization controls based upon endpoints

*Observation:* This is a first stage solution. In a second stage, we should analyze whether the same unification of routes is advisable or not on the backend. And advantage of the current double system in the backend is performance: numerical ids on endpoints are faster to process than long strings. An alternative would be to use a random number instead of long UUIDs as the alternative unique, non-sequential, ID. Sequential IDs are also a problem because they are easily crawlable, making our backend vulnerable to DoS attacks.

**Comment by mitar** [comment]
I think we should not try to optimize here and just use UUIDs in all URLs and make URLs always the same both for public and private. This complexity we are adding just because we worry UUIDs are slow as IDs is unnecessary. I will be closing this and making a more directed issue to address this for good.
