### ISSUE TITLE
Fix commenting on WG page

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1307]
From the public page of a working group, the captcha is hidden for some reason: 

![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/f73353e9-f5fc-411d-a003-8142957aff52)

Test by trying to load directly into your browser a working group page public URL like the followings two: 

https://pb.appcivist.org/#/v2/p/assembly/f5c3bba8-c3dd-40e1-b891-0add8a446615/campaign/0b1e72a2-df31-44f4-ac26-bcef4c667671/group/132f2c7a-f4ed-4091-aa96-1f59becf4bfb

https://pb.appcivist.org/#/v2/p/assembly/0bc7bea3-f253-4824-a9c8-bfedf8998daf/campaign/3de5a9f3-232d-4527-83b6-c850aeaf7388/group/560178d9-d2ca-49ef-840d-3ebe1cb2bed4

You will see the following error in the console: 
If I load the URL directly in the browser, it does not show the captcha

```
ui.js:2 TypeError: recaptcha.render is not a function
    at ui.js:2
    at processQueue (ui.js:2)
    at ui.js:2
    at Scope.$eval (ui.js:2)
    at Scope.$digest (ui.js:2)
    at Scope.$apply (ui.js:2)
    at done (ui.js:2)
    at completeRequest (ui.js:2)
    at XMLHttpRequest.xhr.onload (ui.js:2)
```

However, visiting these working groups public page by clicking on the link from their campaign's page, it does show captcha: 

Go to: https://pb.appcivist.org/#/v2/p/assembly/0bc7bea3-f253-4824-a9c8-bfedf8998daf/campaign/3de5a9f3-232d-4527-83b6-c850aeaf7388 and then click on the WG form a proposal card or from the list of working groups accesible from the toolbar

Go to: https://pb.appcivist.org/#/v2/p/assembly/f5c3bba8-c3dd-40e1-b891-0add8a446615/campaign/0b1e72a2-df31-44f4-ac26-bcef4c667671 and then click on the WG form a proposal card or from the list of working groups accessible from the toolbar

When loading the campaign page, the following error appears in the console (it also appears when loading by simply copying the url in the address bar):
```
ui.js:2 TypeError: Cannot read property '$promise' of undefined
    at loadCampaign (app.js:2)
    at verifyMembership (app.js:2)
    at app.js:2
    at processQueue (ui.js:2)
    at ui.js:2
    at Scope.$eval (ui.js:2)
    at Scope.$digest (ui.js:2)
    at Scope.$apply (ui.js:2)
    at done (ui.js:2)
    at completeRequest (ui.js:2)
    at XMLHttpRequest.xhr.onload (ui.js:2)
```

When I try to comment on a WG page, either on the public page (when i see the captcha) or while being logged in, either choosing to post the comment on the public forumResourceSpace or in the members only resourceSpace, there is an error (this is actually a backend error, see backend logs below). Perhaps @loorely can create a new issue in the backend to properly deal with this: 

```
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179)
	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36)
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36)
	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36)
	at scala.Option.getOrElse(Option.scala:121)
	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:266)
Caused by: java.lang.NullPointerException: null
	at controllers.Contributions.checkRsDraftState(Contributions.java:5542)
	at controllers.Contributions.createContributionInResourceSpaceWithId(Contributions.java:1508)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$263$$anonfun$apply$295.apply(Routes.scala:8188)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$263$$anonfun$apply$295.apply(Routes.scala:8188)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
	at Global$ActionWrapper.call(Global.java:303)
	at http.Headers.call(Headers.java:11)
	at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest.lambda$null$16(AbstractSubjectAction.java:107)
```

To test: you can log in into the Vallejo assembly with either a coordinator or a regular member user, visit last year campaign, visit one of the working group, try to comment. 

The backend error might be due to the following: the UI is trying to post to the wrong resource space id. 

# ToDo

- [x]  Fix captcha problem
- [x] Check that the right backend endpoints are used and also the right resource space ids (for member only, use the workingGroup.resourceSpaceId, for public use the workingGroup.forumResourceSpaceId) 
- [ ] Fix the null pointer exception in the backend and return a proper error description (this is backend, we need an issue in backend @loorely )
