### ISSUE TITLE
CivicBudget Alpha Testing Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#180]
:round_pushpin: Priority
:+1: Was requested during the KO meeting

**Alpha Testing**
- [x] :round_pushpin: Make sure the prototype is refined and fixed by mid-march (see #123)
- [x] :round_pushpin: Find a group of citizens/activists to alpha test the prototype from march to may (e.g., contact PBP project in Oakland) 
- [ ] :round_pushpin: Redesign the onboarding process focusing on the "managed assemblies" use case
- [ ] :round_pushpin: Prepare a pilot testing protocol with clear objectives 

**Documentation:** 
- [x] :round_pushpin: Start a single document where to document all the technical and conceptual information about the prototype
- [ ] :round_pushpin: Create a Database Simplified Data Diagram (to explain relation between concepts)
- [ ] :round_pushpin: Document the conceptual interface of each component of our prototype
- [ ] :round_pushpin: Document the source code organization and how to contribute to the project
- [ ] :round_pushpin: Document the API and how to use it (partially done, but needs cleaning)
- [ ] :+1: Create a User's manual for the Prototype 
- [x] Make a drawing about the different elements of the process)  
- [x] Send 3 slides of appcivist to christoph
- [ ] Share concepts and visual design with Antoine
- [ ] Share technologies in use with Antoine
- [ ] Send “market research” (tools for PB) 
- [ ] Github repository access and HowTo of ticket management system using issues (mission publique will send their user names)

**UI Improvement**
- [ ] :round_pushpin: :+1: Make the UI responsive
- [ ] :+1: Making the proponents and contributors more “visible” (e.g., reputation through points, badges, etc.)
- [ ] Review and redesign the user's homepage, the assembly and the working group pages
- [ ] :round_pushpin: :+1: Review and redesign the visual appeal of the main pages (with Mission Publiques)  

**Translation** 
- [ ] :round_pushpin: :+1: Revise and finalize "english strings"
- [x] :round_pushpin: :+1: Integrate translation strings in all the pages
- [x] :round_pushpin: :+1: Create separate files for french, german and spanish
- [ ] :round_pushpin: :+1: **[Mission Publique]** Translate english strings into priority languages (french and german) 

**Mobilizing component** 
- [ ] :round_pushpin: :+1: Design "meeting scheduling" service and user interface
- [ ] :round_pushpin: :+1: Implement "meeting scheduling" Service
- [ ] :round_pushpin: :+1: Design "group communication" service and user interface
- [ ] :round_pushpin: :+1: Implement "group communication" service and user interface
- [ ] Design a way of integrating the output from a F2F meeting into the platform (e.g., a dedicated mobile app to upload meeting minutes including pictures of meeting generated materials) 

**Assembly Making/Membership Management** 
- [ ] :round_pushpin: :+1: Implement the support for “managed” assemblies (i.e., assemblies where a set of admin users are the only ones empowered to create “ASSEMBLIES”). Alternatively, the regular version would be the "community” version, open for everyone to create assemblies.
- [x] :round_pushpin: Implement "Group Signup"
- [x] :round_pushpin: Implement "Join" assembly/group function
- [x] :round_pushpin: Finish "Verify" invitation page
- [ ] Implement the support for “working groups” to be created not only within campaigns, but at the level of the assembly
- [ ] :round_pushpin: Extend linking assemblies to support the linking at any stage (not only deliberation and voting)
- [ ] :round_pushpin: Simplify/Implement the automated connection of stages in a campaign workflow  
- [ ] Add a rules review stage
- [ ] Monitoring of execution Stage

**Packaging**
- [ ] Simplify the data model of the "CB" prototype (especially, simplify the "campaign" data model)
- [ ] Support the deployment of independent "CB" instances (an instance can be deployed independently by cities and organizations using their own infrastructure)
- [ ] :round_pushpin: :+1: Design how would the "central hub" AppCivist platform would look like and what would be its functions (updates independent instances, keep a registry)
- [ ] :round_pushpin: :+1: Define deployment strategy: investigate what's the best way to package and distribute the platform (e.g., docker?, join back ui with api?, amazon vs heroku vs own server? investigate prices and advantages/disadvantages)

**Archival** 
- [ ] :round_pushpin: :+1: Implement support for versioning data in the system (DB auditing vs archival of “some” things) 

**Voting**
- [ ] :round_pushpin: :+1: Finalize the voting UI
- [ ] :round_pushpin: :+1: Implement the automatic creation of the voting ballot when the voting period starts in a campaign
- [ ] :round_pushpin: F2F/offline voting integration (exporting the ballot as questionnaire, uploading and merging offline votes)

**Vizualizing component** 
- [ ] Design the visualizing component
  - Integrate definition of charts templates
  - Integrate navigation and search of data repositories 
  - Introduce municipal budget simulation as educational tool
  - Integrate polling realization and results visualization for working groups and assemblies(maybe with flash poll)

**Authentication and Privacy** 
- [ ] :round_pushpin: :+1: Define a privacy policy (TU and Inria)
- [ ] Decide if we want to provide Facebook/Google auth (german cities are not allowed to use Facebook as auth provider, check ==> Thentos ==> authentication system from liquiddemocray)
- [ ] Design how to support for anonymity (specially for young people)
