### ISSUE TITLE
i18n checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#190]
For each of the following pages, the following things must be completed to consider the page translated: 
1. Add the following to each controller associated with the page: 

``` javascript
    $scope.user = localStorageService.get("user");
    if ($scope.user && $scope.user.language)
        $translate.use($scope.user.language);    
```
1. In all html partials used by the page, replace $TEXT with {{'$TEXT' | translate}}
2. Add "$TEXT" : "$TEXT" to the locale files with the translation being itself (if $TEXT is too long, use a code instead, e.g., "x.y.z" : "$TEXT"
3. For all the text generated in the controller, use the $translate service in the controller and use it as follows: 

``` javascript
    $scope.translations = [ 'Code 1', 'Code 2', '...' ];
    $translate($scope.translations).then (
        function (translations) {
            $scope.translations = translations;
            // ensure translated strings are associated with scope variables
            $scope.text1 = $scope.translations["Code 1"];
            // ...
        }
    );
```

**Pages Checklist**
When you have finished with the page, mark it as done below. 
:round_pushpin: indicates high priority
**Observation:** notice that each of the following pages is a combination of more than one html partial. To know what partials are used, look for ng-includes, non-standard HTML elements or attributes (they represent "directives") 
- [x] :round_pushpin: Landing Page
- [x] Home Page
- [x] :round_pushpin: Assembly Forum Page
- [x] :round_pushpin: Working Group Forum Page
- [x] :round_pushpin: Campaign Page
- [x] Proposal Read/Edit Page
- [x] Contribution Making Modal
- [x] Assembly Create Page
- [x] :pushpin: Campaign Create Page
- [x] :pushpin: Working Group Create Page
- [x] Voting pages (Ballot registration, Ballot Landing page, Ballot, Vote Summary, Results)
