### ISSUE TITLE
April-May 2016 Test Version Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#204]
:round_pushpin: Priority
:back: Requires backend work
- [x] :round_pushpin: Design and implement edit Campaign page #196
- [x] :round_pushpin: Create consensus voting partial and directive #207
- [x] Integrate usage logging for the proposal making experiment #223
- [x] :round_pushpin: Connect the ConsensusVoting controls to the Voting API to update the vote of the user when they click on them #218
- [x] :round_pushpin: Read "Ballot Results" on campaign loading #215
- [x] :round_pushpin: Create "Ballot Top N Results" partial and directive #216 
- [x] :round_pushpin: Integrate "Ballot Top N" results directive in the campaign page #217
- [ ] :back: :round_pushpin: Complete the implementation of the Working Group Page #198
- [x] Implement user profile update #228
- [ ] :back: :round_pushpin: Create managed instance configuration page #209
- [x] :back: Make sure UpVote and DownVotes are connected to the User #203
- [ ] :round_pushpin: Design and implement edit Working Group page #195
- [ ] :round_pushpin: Design and implement edit Assembly page #194
- [x] :round_pushpin: Improve new proposal creation form with selector for base contributions #199
- [x] :round_pushpin: i18n checklist #190
- [ ] :round_pushpin: Implement filter by themes #139
- [x] :round_pushpin: Fix order by random and popularity in list of comments directive #135
- [x] Fix order by popularity in list of comments directive #220
- [ ] :back: Implement send message #202
- [ ] Implement new layout of home page #201
- [ ] Add support for dynamic configurations of the UI #46
- [ ] Implement landing page for Managed Instance #200
- [x] Design and implement read/edit User Profile page #197
- [ ] Replace the single threaded forum in the assembly page with a multi-threaded forum #191
- [ ] Integrate loading icon to pages #193
- [ ] Integrate FlashService messages into pages #192
