### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#328]
## Describe the problem/story
In version 2, we need support for storing and retrieving "managed instance configurations". A managed instance represents either an installation of the platform or one instance of the service available at appcivist.org. This will affect the creation patterns, which need to be redesigned both in style and options. 

## Some notes to take into account for this epic
- [ ] In appcivist.org, Users can create a "managed instance" of the AppCivist service: this will include one "Main Assembly" and a package of assemblies, campaigns and WGs they can create per year, along with a number of members they can support in their assemblies. 
- [ ] New assemblies are created under the main assembly and must be added to its resource space
- [ ] The new assembly form must be reviewed to remove the "linked assemblies" step
- [ ] Campaigns are created inside assemblies, but part of their stages can be share among multiple campaigns, accross multiple assemblies
- [ ] WGs are always created inside of campaigns
- [ ] What will the assembly page provide? Probably, just a message board for members and information about the ongoing activity in its campaigns and WGs

### Principal Assemblies Configurations
Some assemblies will represent **principal assemblies** (i.e., assemblies that represent a managed instance of the AppCivist Service). Principal assemblies serve as the main hub for a user, accessible through a specific domain or path in the URL. Every user must be a member of at least one **principal assembly**. To register, Users create an account and join a principal assembly. The following are configuration keys to be associated with a principal assembly and that applies to all the elements under it:  

* **appcivist.instance.assembly-network:** if TRUE, it allows COORDINATORS of the principal assembly to create new and manage other assemblies under the principal one. 
* **appcivist.instance.assembly-network-limit:** number of Assemblies that can be created in the network.
* **appcivist.instance.assembly-network-campaign-limit:** number of ongoing Campaign (per assembly) that can be created in the network.
* **appcivist.instance.assembly-network-working-group-limit:** number of Working Groups (per assembly and campaign) that can be created in the network.
* **appcivist.instance.etherpad-base-url:** Base URL of the Etherpad server in use by this instance
* **appcivist.instance.etherpad-api-key:** (only for COORDINATORS) configures the Etherpad API key in case the coordinators decide to use their own etherpad server instance
* **appcivist.instance.domain:** domain registered to the instance (when Signing in, the server will determine the principal assembly associated to the user by reading the domain from where the request is coming from)
* **appcivist.instance.api-key:** a generated secret code that can be use by apps to connect to the API and access information of assemblies, campaigns, working groups and contributions on this instance. 
* **appcivist.instance.theme:** a URL that points to a CSS files that will overwrite the color scheme of the site for this assembly

**Observations:** when users register to more than one principal assembly, the domain from which they signed in will determine what assembly to load.  

**ToDo:**
* Add field to identify assemblies as Principal to the model of Assembly
* Add field to include the principal assembly in the Users Sign up form
* Create the Assembly Configuration Page to update these values (only for Coordinators) 
* Update the UI to use these configurations to: (1) decide what assembly and campaign to load as homepage, (2) determine what etherpad base URL to use to display proposal texts, (3) know how many assemblies, campaigns and WG the coordinators can still create, (4) include the domain from where the user signed in in all requests

### Assembly configurations
* **appcivist.assembly.enable-forum:** if TRUE, an assembly page will be the home page after signing in (this assembly page has not been designed yet)
* **appcivist.assembly.disable-new-memberships:** only coordinators can add new members to the assembly, by uploading users for them.   
* **appcivist.assembly.membership-type:** REGISTRATION (other users ask to join), INVITATION (members invite other users) or INVITATION_AND_REGISTRATION. 
* **appcivist.assembly.membership-invitation-by-members:** if TRUE, regular members can invite other users to join, otherwise only COORDINATORS have this right
* **appcivist.assembly.has-registration-form:** if TRUE, to join the assembly, users must fill in a registration form
* **appcivist.assembly.has-registration-form-url:** a URL to an external registration form
* **appcivist.assembly.has-registration-form-id:** an ID that represents an internal registration form use 
* **appcivist.assembly.enable-moderator-role:** if TRUE, members can also have the role MODERATOR, which allows a member to delete content (comments, proposals, ideas, etc.)

**ToDo**
* Create the RegistrationForm Model (we can simply reuse the VotingBallotRegistrationForm table and make it general to the whole site
* Include the configurations in this list in the creation of an assembly

### Campaign configurations
* **appcivist.campaign.hide-timeline:** if TRUE, the timeline of the campaign is hidden and the campaign has only one stage
* **appcivist.campaign.contribution-types:** and array that contains the list of contribution TYPES collected in this campaign (IDEA, PROPOSAL, NOTE, etc.)  
* **appcivist.campaign.contribution-type-principal:** what type of contribution is the displayed at the center of the page if a timeline with components is disabled (e.g., these campaigns is centered around PROPOSALS or IDEAS)    
* **appcivist.campaign.disable-discussions:** if TRUE, the comment sections in the campaign dashboard is disabled 
* **appcivist.campaign.disable-public-site:** if TRUE, the campaign does not have a public site
* **appcivist.campaign.disable-public-discussions:** if TRUE, the comment sections is hidden in public site
* **appcivist.campaign.disable-informal-voting:** if TRUE, up and down votes are disabled
* **appcivist.campaign.disable-informal-voting-public:** if TRUE, up and down votes are disabled in the public site
* **appcivist.campaign.disable-extended-feedback:** if TRUE, extended feedback is disabled 
* **appcivist.campaign.disable-extended-feedback-public:** if TRUE, extended feedback is disabled in the public site
* **appcivist.campaign.disable-new-contributions:** if TRUE, contributions can only be imported by COORDINATORS, members will not be able to create ideas or proposals
* **appcivist.campaign.disable-etherpad:** if TRUE, proposals do not have an etherpad extended text attached, only a description field. 

**ToDo**
* Integrate these configurations in the site to control what to show and what not to show
* Create a "update campaign" page to manage this configurations (accessible only to COORDINATORS of the assembly)
* Include the configurations in the UPDATE campaign page list in the creation of an assembly

### Component (Phase) configurations  
* **appcivist.component.contribution-type-principal:** what type of contribution is the displayed at the center of the page when this component in the timeline is current (e.g., in Idea Collection, the main contribution type will be IDEAS)
* **all the other configuration keys of the campaign, can be overridden in each component**

**ToDo**
* Integrate these configurations in the site to control what to show and what not to show
* Create a "update campaign" page to manage this configurations (accessible only to COORDINATORS of the assembly)
* Include the configurations in the UPDATE campaign page list in the creation of an assembly

### Working Group configurations
* **appcivist.wg.membership-type:** REGISTRATION (other users ask to join), INVITATION (members invite other users) or INVITATION_AND_REGISTRATION. 
* **appcivist.wg.membership-invitation-by-members:** if TRUE, regular members can invite other users to join, otherwise only COORDINATORS have this right
* **appcivist.wg.has-registration-form:** if TRUE, to join the assembly, users must fill in a registration form
* **appcivist.wg.has-registration-form-url:** a URL to an external registration form
* **appcivist.wg.has-registration-form-id:** an ID that represents an internal registration form use 
* **appcivist.wg.enable-moderator-role:** if TRUE, members can also have the role MODERATOR, which allows a member to delete content (comments, proposals, ideas, etc.)
* **appcivist.wg.disable-public-site:** if TRUE, the working group is not available in the public site
