### ISSUE TITLE
Membership Controls

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#332]
## Describe the problem/story
WGs pages should display buttons to join the WG and add member should allow coordinators to invite people to join

## Specifications for the story

- [x] Add join button for non-members of WG
- [x] Allow COORDINATORS to invite people
- [x] Allow COORDINATROS to accepte pending requests
