### ISSUE TITLE
September 27th Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#59]
Checklist/Roadmap for the next demo, in order of priority. There are associated issues for each item. Let's do as much as we can for September 27th API Documentation [Local](https://localhost:9000/api/doc) | [Heroku](https://appcivist-pb.herokuapp.com/api/doc)
1. **New Assembly**
   - [x] #67 Finalize assembly creation workflow, adding the step 3
2. **Campaign Page Starting Brainstorming**
   - [x] #68 Paint Component's Timeline
   - [x] #69 Take milestones text from campaign.resources.components.milestones
     - Display the date of start for that milestones using something like http://momentjs.com/docs/#/displaying/to/
   - [ ] #70 Add modal window for contributions and then POST /assembly/{id}/campaign/{id}/component/{id} contribution
   - [ ] #71 Display detail and comments of contribution in modal window
   - [x] #72 List contributions from the list of contributions in the current component resourceSpace
   - [x] #73 Remove pagination, let's just have an infinite scrolling
   - [x] #74 Link search box in campaign page 
3. **New Campaign**
   - [x] #75 Change "Next" in Step5 for "Start Campaign" and link it to the POST and then Campaign Page
   - [x] #76 Add back button to each step in the campaign creation
   - [x] #77 Show/display the right side "campaign template" or a "linked campaign" only after a template is selected to the left
   - [ ] #78 connect list of campaign templates to API => GET /campaign/template
   - [ ] #79 Replace the list of campaigns to link with a button that opens a modal window for searching the possible campaigns to link to
   - [ ] #80 Connect fastrack button to POST /assembly/{id}/campaign using default values for all the configs and adding all the themes of the assembly 
4. **Home**
   - [ ] #56 Links in the side bar
     - Link assemblies names also to /#/assembly/{uuid} 
     - Link campaign names also to /#/assembly/{uuid}/campaign/{uuid} 
     - Link group names also to /#/assembly/{uuid}/group/{uuid} 
     - Link "Go to... " to one of the assemblies/campaigns/groups in the list of the user 
     - Link upcoming milestone text to the corresponding campaign => use the update.resourceUuid to select the corresponding campaign => /#/assembly/{uuid}/campaign/{uuid}  
5. **Single Assembly Page**
   - [ ] #65 Link contribution buttons: 
     - "Publish" => POST /assembly/{id}/contribution?space=forum
     - "Cancel" => Clean the contribution form
     - "Select Theme" => fill up options using the assembly themes 
     - "+" must open allow attaching a file  
   - [ ] As in #56, link elements in the side bar
   - [ ] #62 Show members list =>  GET /assembly/{id}/membership/status=ACCEPTED
   - [ ] #63 Show campaign list =>  GET /assembly/{id}/campaign
   - [ ] #64 Show working group list =>  GET /assembly/{id}/group
   - [ ] #61 Show/hide buttons according to membership
   - [ ] #66 Link "Invite participants" button 
     - Open a modal window
     - Ask invitation emails separated by comma and a field with the invitation message
     - POST /assembly/{id}/invitations
6. **Nav Bar**
   - [x] #57 Show the user profile icon and name
   - [x] #58 Use inbox-icon
   - [ ] Add titles of current focus after "Assemblies"
     - When in an "Assembly"
7. **Assemblies Page**
   - [x] As in #56, link elements in the side bar
   - [ ] When reloading the page, reload in the assembly not home
   - [x] #58 Use inbox-icon
   - [x] #60 Search button and searchbox 
     - "Filter..." instead of "Search for..." in the searchbox 
     - Link the search button to the query endpoint and replace the list with the search result
8. **Landing page**
   - [ ] #43 Signup   => /#/signup => POST /user/signup => /#/
   - [x] #53 Add "show more" buttons next to current assemblies searchbox
   - [x] #54 Enlarge icons of Assemblies Components
   - [ ] #55 Link each current assembly to its assembly page
