### ISSUE TITLE
Refinement and fixes to new Create IDEA Form 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#693]
[!image](https://files.slack.com/files-tmb/T0GH49XJ5-F5JRF8SE4-0693fb907c/pasted_image_at_2017_05_29_05_22_pm_720.png) 

## ToDo list for idea creation form in order of priority: 

- [x] **NON_MEMBER_AUTHOR custom fields:** for each custom fields, if `entityType` === `NON_MEMBER_AUTHOR`, then they refer to author info and must go under that section, after Phone number, under a title `Optional Survey Information`
- [x] **Option values:** show options for custom fields of `fieldType` === `MULTIPLE_CHOICE`. For the options, look into the property `customFieldValueOptions`, which is a list with all the options.  If `limit` of custom field is `1`, then use `radio buttons`. If `limit` es `MULTIPLE`, then use checkboxes. Moreover, if the option `value_type` is `STRING_OPEN`, then display a text field to get the value. 
- [x] **IDEA custom fields:** show idea custom fields before author info. Show only custom fields where `entityType` === `CONTRIBUTION`, `entityFilterAttributeName` === 'type' and  `entityFilter` == ‘IDEA’ (i.e., contribution custom fields that are only for contribution where the attribute `type` is equal to `IDEA`.
- [x] Add button to edit cover
- [x] Add loading wheel when clicked on save
- [x] Replace save by `Save and submit`
- [x] Add the idea to the campaign content
- [x] Add disclaimer text before author  section
```
Personal and identifying information, including names, e-mails, and phone numbers, will never be shared or published. Any survey information is confidential and anonymous, and will only be used in aggregate form to help researchers evaluate the success and effectiveness of the '[campaign_title]' program.
```
- [x] Remove the title "Title of Idea" and leave only the field
- [x] Replace Description with `What’s your idea for '[campaign_title]'*`
- [x] Add the following sub-text under the description title `Where will this occur? Who will benefit? Why is this needed?`
- [x] Add the following under the `Themes`
```
Click on the field to see the list of Themes of '[campaign_title]'. Select the theme(s) that best categorize your idea. Select at least one theme.
```
- [x] Add the following udner keywords
```
Add the keywords that best describe your idea. Write one keyword at a time. Press enter to confirm the keyword. 
```
- [x] Add info tooltip for keyword
```
 Example: If you’re idea is for new bike lanes, the theme might be “Transportation” and one keyword would be “cycling”
```
- [x] Increase font sizes

**Comment by cdparra** [comment]
Some additional issues: 
- [ ] MULTIPLE choice checkboxes are all selected together
![image](https://cloud.githubusercontent.com/assets/630150/26567087/712914a8-44c6-11e7-8ab9-6dc878e25c83.png)

- [ ] Retrieve information of author when email is added (all its custom fields) 
- [ ] Persist non member author custom values

**Comment by cdparra** [comment]
One last item: 

- [ ] Add captcha to the form when user is not logged in

**Comment by cdparra** [comment]
- [ ] Error on campaign dashboard after integrating new card designs and modifying dashboard to show ideas at center: 

![image](https://cloud.githubusercontent.com/assets/630150/26590401/71b35f84-4528-11e7-86da-117a9c9d3c73.png)
