### ISSUE TITLE
Campaign voting components integration

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#814]
When the campaign current component is of type VOTING, the following should be implemented: 

- [x] Show at the center of the page contributions of type `ballot.entityType`
- [x] If `campaign.externalBallot` is not empty, use the voting instructions modal to display the message: `Voting for [campaign title] takes place outside of AppCivist. Follow this <link> to learn more and vote. You can still use AppCivist to view the proposals that were included on the ballot`. link = `campaign.externalBallot`
- [x] If `campaign.currentBallot` is empty use the voting instructions modal to display the message: `The Voting Ballot for [campaign title] is being prepared and will be announced soon. Stay tuned and come back when is ready!`

If (`user logged in` && `externalBallot` is empty && `currentBallot` is not empty)
- [x] Try to read the ballot paper of the user: `GET /api/v0/ballot/:ballot_uuid/vote/:signature`. `ballot_uuid = campaign.bindingBallot`, `signature = user.uuid`. 
- [x] If the user does not have a ballot paper yet (previous endpoint response is 404), connect a `Start Voting` button to the following endpoint, sending the user `uuid` as signature and the `campaign.ballotIndex[campaign.currentBallot].password` in the body. The ballot secret code will be in `campaign.ballotIndex[campaign.currentBallot].password` only for logged in users.
```
POST  /api/v0/ballot/:ballot_uuid/vote  
{
  "vote": {
    "signature": "[user.uuid]",
  },
  "password": "[`campaign.ballotIndex[campaign.currentBallot].password`]"
}
```
- [ ] If user does not have ballot paper, use `GET /api/v0/ballot/:ballot_uuid/registration` to get the ballot info, that contains the instructions
- [ ] Connect `Save Votes` controls to `PUT /api/v0/ballot/:ballot_uuid/vote/:signature` (see below the format for the votes to send and how to relate each contribution with a candidate)
- [ ] Connect `Finalize Voting` to `PUT /api/v0/ballot/:ballot_uuid/vote/:signature/complete`
- [ ] Use the ballot `limit` (i.e., a integer number) and `limitType` (VOTES, TOKENS). To control the interaction with votes. If limitType is VOTES, display how many proposals left to vote there are for the user. If the limitType is TOKENS, display how many points left to vote there are for the user. 
- [ ] When limit of votes is exceded, display all the remaining non voted proposals as grayed out with voting controls disabled. 
- [ ] Disable WG links in the cards when voting stage has started 

If (`user NOT logged in` && `externalBallot` is empty && `currentBallot` is not empty)

- [ ] For public site, show the password field and ask the user to provide it along with an email. use `GET /api/v0/ballot/:ballot_uuid/registration` to get the ballot info, that contains the instructions

**Vote format**

Has two parts: 
- The ballot, which contains an array of "candidates" and a "candidateIndex" which relates each candidate UUID (which is the contribution UUID) for a place in that candidate array where it has the "candidate_id"
- The votes, which has an array of votes (each with an candidate_id, the value of the vote and the value tyep). and an index of votes to access that array more quickly by id
- Each vote controller has to be connected to this array

```json
{
    "ballot": {
        "uuid": "daaf1a92-35cc-4300-91f0-88b8546a1de4",
        "voting_system_type": "DISTRIBUTED",
        "instructions": "<p><h1>The voting stage has begun!</h1></p>\n<p>For this round of voting you wil have 100 points each that you can distribute across as many proposals as you want.</p>\n<p>You must utilize all your points in order for your vote to be considered.</p>\n<p>You can change your vote until <voting end date>. A er this you cannot change your votes.</p>\n<p>The 3 proposals with the highrest number of points will be selected as the winning proposals at the end of the voting stage.</p>\n<p>In case of a tie, the number of participants who voted for those proposals would be taken into consideration. The proposal with higher number of participants will be considered as the winner of the tie.</p>",
        "notes": null,
        "votes_limit": "20",
        "votes_limit_meaning": "TOKENS",
        "ballot_configurations": [],
        "candidates": [
            {
                "id": 129,
                "ballot_id": 180,
                "uuid": "050a3dc8-09fb-482e-be2d-cc032c6346ec",
                "candidate_type": 1,
                "candidate_uuid": "9da03c3e-b446-4844-9b09-6ef838edcf9f",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 130,
                "ballot_id": 180,
                "uuid": "c8114906-c55c-4b4e-aae4-221eba1d18df",
                "candidate_type": 1,
                "candidate_uuid": "ba454b68-1213-4783-b523-1fc977429eb7",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 131,
                "ballot_id": 180,
                "uuid": "72c7f723-6321-4533-99ec-24ae49bc7ee0",
                "candidate_type": 1,
                "candidate_uuid": "1d5164f4-6f04-46ee-8fcb-8edf55f88607",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 132,
                "ballot_id": 180,
                "uuid": "3174ffea-31ac-4b5d-b6a6-aa13aca236e8",
                "candidate_type": 1,
                "candidate_uuid": "048becd0-5391-4a71-846c-b3cff871d16a",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 133,
                "ballot_id": 180,
                "uuid": "23ff199b-f3fc-4446-ba68-b7daf53b2334",
                "candidate_type": 1,
                "candidate_uuid": "02a5c1d3-3e43-4b28-a9ea-7767d2b2b585",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 134,
                "ballot_id": 180,
                "uuid": "ba8ab9d8-fb2e-49ac-90c9-50fb58b574b3",
                "candidate_type": 1,
                "candidate_uuid": "9a43a1e1-f03f-49e8-b9b2-6a9a92561705",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 135,
                "ballot_id": 180,
                "uuid": "f5300a92-8df5-402b-8dfc-1e450c4b2a10",
                "candidate_type": 1,
                "candidate_uuid": "2c98ffbd-183a-48d3-8845-f168ad7e872e",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 136,
                "ballot_id": 180,
                "uuid": "cb73661f-0593-42a8-b966-da789b129292",
                "candidate_type": 1,
                "candidate_uuid": "fa808a15-e627-4413-bda8-48cb6eac2e0d",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 137,
                "ballot_id": 180,
                "uuid": "0f20c732-4660-44cf-9732-bbe88c86b897",
                "candidate_type": 1,
                "candidate_uuid": "16a2e72b-5603-40b5-a0c4-f3b2e9d4a994",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 138,
                "ballot_id": 180,
                "uuid": "1ec3a0ab-4169-45c9-b511-fa1a0b1a6207",
                "candidate_type": 1,
                "candidate_uuid": "c6daa314-f594-4e02-b48d-656b824140f6",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            }
        ],
        "candidatesIndex": {
            "9da03c3e-b446-4844-9b09-6ef838edcf9f": 0,
            "ba454b68-1213-4783-b523-1fc977429eb7": 1,
            "1d5164f4-6f04-46ee-8fcb-8edf55f88607": 2,
            "048becd0-5391-4a71-846c-b3cff871d16a": 3,
            "02a5c1d3-3e43-4b28-a9ea-7767d2b2b585": 4,
            "9a43a1e1-f03f-49e8-b9b2-6a9a92561705": 5,
            "2c98ffbd-183a-48d3-8845-f168ad7e872e": 6,
            "fa808a15-e627-4413-bda8-48cb6eac2e0d": 7,
            "16a2e72b-5603-40b5-a0c4-f3b2e9d4a994": 8,
            "c6daa314-f594-4e02-b48d-656b824140f6": 9
        }
    },
    "vote": {
        "uuid": "9d624404-d2f8-495f-911f-9d2460e8856b",
        "signature": "pincopallino",
        "status": 0,
        "votes": [
            {
                "candidate_id": 129,
                "value": "5",
                "value_type": null
            },
            {
                "candidate_id": 130,
                "value": "2",
                "value_type": null
            },
            {
                "candidate_id": 131,
                "value": "3",
                "value_type": null
            }
        ],
        "votesIndex": {
            "129": 0,
            "130": 1,
            "131": 2
        }
    }
}

```

**For ballot results**
- [ ] Ballot results modal should be connected to `GET /api/v0/ballo/:ballot_uuid/results`
the model is similar to the ballot object, only now there is also a results an index, which funcitons as quick access to the each candidate, with its summarized list of votes and final score. 

```json
{
    "ballot": {
        "uuid": "daaf1a92-35cc-4300-91f0-88b8546a1de4",
        "finished": false,
        "candidates": [
            {
                "id": 129,
                "ballot_id": 180,
                "uuid": "050a3dc8-09fb-482e-be2d-cc032c6346ec",
                "candidate_type": 1,
                "candidate_uuid": "9da03c3e-b446-4844-9b09-6ef838edcf9f",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 130,
                "ballot_id": 180,
                "uuid": "c8114906-c55c-4b4e-aae4-221eba1d18df",
                "candidate_type": 1,
                "candidate_uuid": "ba454b68-1213-4783-b523-1fc977429eb7",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 131,
                "ballot_id": 180,
                "uuid": "72c7f723-6321-4533-99ec-24ae49bc7ee0",
                "candidate_type": 1,
                "candidate_uuid": "1d5164f4-6f04-46ee-8fcb-8edf55f88607",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 132,
                "ballot_id": 180,
                "uuid": "3174ffea-31ac-4b5d-b6a6-aa13aca236e8",
                "candidate_type": 1,
                "candidate_uuid": "048becd0-5391-4a71-846c-b3cff871d16a",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 133,
                "ballot_id": 180,
                "uuid": "23ff199b-f3fc-4446-ba68-b7daf53b2334",
                "candidate_type": 1,
                "candidate_uuid": "02a5c1d3-3e43-4b28-a9ea-7767d2b2b585",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 134,
                "ballot_id": 180,
                "uuid": "ba8ab9d8-fb2e-49ac-90c9-50fb58b574b3",
                "candidate_type": 1,
                "candidate_uuid": "9a43a1e1-f03f-49e8-b9b2-6a9a92561705",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 135,
                "ballot_id": 180,
                "uuid": "f5300a92-8df5-402b-8dfc-1e450c4b2a10",
                "candidate_type": 1,
                "candidate_uuid": "2c98ffbd-183a-48d3-8845-f168ad7e872e",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 136,
                "ballot_id": 180,
                "uuid": "cb73661f-0593-42a8-b966-da789b129292",
                "candidate_type": 1,
                "candidate_uuid": "fa808a15-e627-4413-bda8-48cb6eac2e0d",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 137,
                "ballot_id": 180,
                "uuid": "0f20c732-4660-44cf-9732-bbe88c86b897",
                "candidate_type": 1,
                "candidate_uuid": "16a2e72b-5603-40b5-a0c4-f3b2e9d4a994",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            },
            {
                "id": 138,
                "ballot_id": 180,
                "uuid": "1ec3a0ab-4169-45c9-b511-fa1a0b1a6207",
                "candidate_type": 1,
                "candidate_uuid": "c6daa314-f594-4e02-b48d-656b824140f6",
                "created_at": "2017-09-14T14:20:54.680Z",
                "updated_at": "2017-09-14T14:20:54.680Z",
                "removed_at": null,
                "removed": false
            }
        ],
        "candidatesIndex": {
            "9da03c3e-b446-4844-9b09-6ef838edcf9f": 0,
            "ba454b68-1213-4783-b523-1fc977429eb7": 1,
            "1d5164f4-6f04-46ee-8fcb-8edf55f88607": 2,
            "048becd0-5391-4a71-846c-b3cff871d16a": 3,
            "02a5c1d3-3e43-4b28-a9ea-7767d2b2b585": 4,
            "9a43a1e1-f03f-49e8-b9b2-6a9a92561705": 5,
            "2c98ffbd-183a-48d3-8845-f168ad7e872e": 6,
            "fa808a15-e627-4413-bda8-48cb6eac2e0d": 7,
            "16a2e72b-5603-40b5-a0c4-f3b2e9d4a994": 8,
            "c6daa314-f594-4e02-b48d-656b824140f6": 9
        }
    },
    "results": [
        {
            "candidate_id": 131,
            "values": [
                "3",
                "3"
            ],
            "candidate_uuid": "1d5164f4-6f04-46ee-8fcb-8edf55f88607",
            "score": 6
        },
        {
            "candidate_id": 128,
            "values": [
                "5"
            ],
            "candidate_uuid": "40cb1750-f0aa-11e5-9ce9-5e5517507c66",
            "score": 5
        },
        {
            "candidate_id": 129,
            "values": [
                "5"
            ],
            "candidate_uuid": "9da03c3e-b446-4844-9b09-6ef838edcf9f",
            "score": 5
        },
        {
            "candidate_id": 130,
            "values": [
                "2",
                "2"
            ],
            "candidate_uuid": "ba454b68-1213-4783-b523-1fc977429eb7",
            "score": 4
        }
    ],
    "index": {
        "1d5164f4-6f04-46ee-8fcb-8edf55f88607": {
            "vote": {
                "candidate_id": 131,
                "values": [
                    "3",
                    "3"
                ],
                "candidate_uuid": "1d5164f4-6f04-46ee-8fcb-8edf55f88607",
                "score": 6
            },
            "position": 0
        },
        "40cb1750-f0aa-11e5-9ce9-5e5517507c66": {
            "vote": {
                "candidate_id": 128,
                "values": [
                    "5"
                ],
                "candidate_uuid": "40cb1750-f0aa-11e5-9ce9-5e5517507c66",
                "score": 5
            },
            "position": 1
        },
        "9da03c3e-b446-4844-9b09-6ef838edcf9f": {
            "vote": {
                "candidate_id": 129,
                "values": [
                    "5"
                ],
                "candidate_uuid": "9da03c3e-b446-4844-9b09-6ef838edcf9f",
                "score": 5
            },
            "position": 2
        },
        "ba454b68-1213-4783-b523-1fc977429eb7": {
            "vote": {
                "candidate_id": 130,
                "values": [
                    "2",
                    "2"
                ],
                "candidate_uuid": "ba454b68-1213-4783-b523-1fc977429eb7",
                "score": 4
            },
            "position": 3
        }
    }
}
```
