### ISSUE TITLE
October 5th Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#85]
Checklist/Roadmap for the next demo, in order of priority. There are associated issues for each item. Let's do as much as we can for September 27th API Documentation [Local](https://localhost:9000/api/doc) | [Heroku](https://appcivist-pb.herokuapp.com/api/doc)
1. **Campaign Page Starting Brainstorming**
   - [x] #70 Add modal window for contributions and then POST /assembly/{id}/campaign/{id}/component/{id} contribution
   - [ ] #71 Display detail and comments of contribution in modal window
2. **New Campaign**
   - [ ] #77 Check comments for update on how to manage hide/display of right side
   - [ ] #78 connect list of campaign templates to API => GET /campaign/template
   - [ ] #80 Connect fastrack button to POST /assembly/{id}/campaign using default values for all the configs and adding all the themes of the assembly (before, let's do the group related pages) 
3. **Working Group Page**
   - [ ] #84 Create a first version of the working group page (following Assembly example) 
4. **Home**
   - [x] #56 Links in the side bar
     - Link assemblies names also to /#/assembly/{uuid} 
     - Link campaign names also to /#/assembly/{uuid}/campaign/{uuid} 
     - Link group names also to /#/assembly/{uuid}/group/{uuid} 
     - Link "Go to... " to one of the assemblies/campaigns/groups in the list of the user 
     - Link upcoming milestone text to the corresponding campaign => use the update.resourceUuid to select the corresponding campaign => /#/assembly/{uuid}/campaign/{uuid}  
5. **Single Assembly Page**
   - [ ] #65 Link contribution buttons: 
     - "Publish" => POST /assembly/{id}/contribution?space=forum
     - "Cancel" => Clean the contribution form
     - "Select Theme" => fill up options using the assembly themes 
     - "+" must open allow attaching a file  
   - [x] As in #56, link elements in the side bar
   - [ ] #62 Show members list =>  GET /assembly/{id}/membership/status=ACCEPTED
   - [ ] #63 Show campaign list =>  GET /assembly/{id}/campaign
   - [ ] #64 Show working group list =>  GET /assembly/{id}/group
   - [ ] #61 Show/hide buttons according to membership
   - [ ] #66 Link "Invite participants" button 
     - Open a modal window
     - Ask invitation emails separated by comma and a field with the invitation message
     - POST /assembly/{id}/invitations
6. **Nav Bar**
   - [ ] Add titles of current focus after "Assemblies"
     - When in an "Assembly"
7. **Assemblies Page**
   - [ ] When reloading the page, reload in the assembly not home
8. **Landing page**
   - [x] #43 Signup   => /#/signup => POST /user/signup => /#/
   - [ ] #55 Link each current assembly to its assembly page (check for the comment on issue how to proceed)
9. Versioning
   - [ ] #86  Read View of Proposals following [this mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNNnF5dDlLTW5HZ0U)
   - [ ]  #87 Edit View of Proposals following [this mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNdzNqaW9pYlh2Nmc) and integrating etherpad

**Notes about JSON models**
- [Assembly](http://www.jsoneditoronline.org/?id=97b4cdfea93b8a118e19d7a7325c0c9a) (everything is returned right now, posts in forum, campaigns, including also all the content of the campaign, this will be limited in the future for more efficiency and better control access)
- [Contribution](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e91304138b1)
- [Campaign](http://www.jsoneditoronline.org/?id=e6796dc77cf32a37a4639a606bad3c48)
- [Component Instance](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e455c817)
- [Milestone](http://www.jsoneditoronline.org/?id=a1d1a89c08de9ad2b2ee736d4e9622fd)
- [Working Group](http://www.jsoneditoronline.org/?id=06d4351927ade6b8b81d54a4e4575707)
- [New Assembly](http://www.jsoneditoronline.org/?id=645ab1a29503c4bbd9aaa03d103a1700)
- [New Contribution](http://www.jsoneditoronline.org/?id=9bf3de782191b0caf8ede60f672cf272) (type = FORUM_POST if it is for the forum, IDEA if it is a contribution for brainstorming, PROPOSAL if it is for the stages after brainstorming) 
- [New Campaign](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25)
- [New Working Group](http://www.jsoneditoronline.org/?id=b182e25563f1e09264af8e913058f0d4)
- [Listed Assembly Profiles](http://www.jsoneditoronline.org/?id=6f27b15c8eca3b4b261a9fdbb5e21cf5)
- [List of Assembly Campaigns](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f21a171) 
- [List of Contributions](http://www.jsoneditoronline.org/?id=f7aec5423dde608f9fb7dfbf3f4fa3c7)

[New Campaign Example](http://www.jsoneditoronline.org/?id=36f5ad7ad03879d08d4515195d511d25) update. Because we cannot use ebean to merge existing a new entities in relationships, the new model now must specify which entities (themes, components) are existing in a different array.
