### ISSUE TITLE
Voting Ballot UI Checklist

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#92]
1. Create a branch from Develop called "Voting UIs"
2. Create the folder "voting" inside of the folder "partials"
3. Create and add to this folder the HTML version of each of the following screens in the mockup (for the case of range voting)
- [x] Voting Ballot Landing Page ([mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNVGhndkd5czFiczA))
- [x] Voting Ballot Voting Page ([mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNZjEyS040aWdkMWs))
- [x] Voting Ballot Voting Summary ([mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNdGgxSnBTLTlhY2M))
- [x] Voting Ballot Voting Results Page ([mockup](https://drive.google.com/open?id=0B7ShzcEnCJFNNUVSWEFSX3l2eXc))
